use_frameworks!

platform :ios, '8.0'

target 'TLColorFlowLayout_Example' do
  pod 'TLColorFlowLayout', :path => '../'

  target 'TLColorFlowLayout_Tests' do
    inherit! :search_paths

    
  end
end
